version: '3'

services:

  backend:
    image: "inventory-server"
    container_name: "inventory-server"
    ports: 
      - 3000:3000
    environment:
      - MONGO_URI=db
    links:
      - db

  db:
    image: "mongo"
    container_name: "mongo-db"
    ports: 
      - 27018:27017
